# Generated by Django 5.1.1 on 2024-10-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=20)),
                ('is_night', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_reservable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoothDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_description', models.TextField(blank=True)),
                ('entrace_fee', models.IntegerField(default=0)),
                ('menus', models.TextField(blank=True)),
                ('tabling_link', models.TextField(blank=True)),
                ('insta_id', models.CharField(blank=True, max_length=50)),
                ('insta_link', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booth/')),
                ('is_nignt', models.BooleanField(blank=True, default=False)),
                ('is_reservable', models.BooleanField(blank=True, default=False)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('host', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booth.booth')),
            ],
        ),
    ]
