# Generated by Django 5.1.1 on 2024-10-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boothdetail',
            old_name='is_nignt',
            new_name='is_night',
        ),
        migrations.RemoveField(
            model_name='boothdetail',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booth/')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
    ]
