# Generated by Django 5.1.1 on 2024-09-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_description', models.TextField(blank=True)),
                ('entrace_fee', models.IntegerField(default=0)),
                ('menus', models.TextField(blank=True)),
                ('tabling_link', models.TextField(blank=True)),
                ('insta_id', models.CharField(blank=True, max_length=50)),
                ('insta_link', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booth/')),
                ('like_count', models.IntegerField(default=0)),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booth.booth')),
            ],
        ),
    ]
