# Generated by Django 5.1.1 on 2024-10-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_boothdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='is_reservable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boothdetail',
            name='is_reservable',
            field=models.BooleanField(default=False),
        ),
    ]
