# Generated by Django 5.1.1 on 2024-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_boothdetail_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothdetail',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='booth',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='booth/'),
        ),
    ]
