# Generated by Django 5.1.1 on 2024-10-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_remove_image_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='booth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booth.booth'),
            preserve_default=False,
        ),
    ]
