# Generated by Django 5.1.1 on 2024-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=200)),
                ('info', models.TextField(max_length=200)),
                ('insta_id', models.CharField(max_length=50)),
                ('insta_link', models.URLField()),
            ],
        ),
    ]
