# Generated by Django 5.1.1 on 2024-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('fire', models.CharField(default='🔥', max_length=1)),
                ('fire_count', models.IntegerField(default=0)),
            ],
        ),
    ]
