# Generated by Django 5.1.1 on 2024-09-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_fire_fire_alter_fire_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='insta_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
