# Generated by Django 5.1.1 on 2024-09-24 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_fire_day_alter_timetable_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_song', models.CharField(blank=True, max_length=100, null=True)),
                ('show_info', models.TextField(blank=True, null=True)),
                ('insta_id', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable')),
            ],
        ),
    ]
